language: python
python:
  - "3.8.5"      # current default Python on Travis CI
# command to install dependencies
install:
sudo pip3 install --upgrade pip
  - pip install -r requirements.txt
notifications:
  email:
    recipients:
      - aakashv.8292@gmail.com
    on_success: never # default: change
    on_failure: always # default: always