language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
virtualenv:
  system_site_packages: true
notifications:
  email:
    recipients:
      - aakashv.8292@gmail.com
    on_success: never # default: change
    on_failure: always # default: always