language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
notifications:
  email:
    recipients:
      - aakashv.8292@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
sudo: required
services:
  - docker
before_install:
  -docker build -f Dockerfile.dev .